### ISSUE TITLE
YouTube Danmaku Documentation?

### ISSUE THREAD

**Issue by JomSpoons** [siikamiika/scripts#1]
I'm a bit confused as to how I'm supposed to use YouTube Danmaku. A quick guide would be appreciated. Thanks.

**Comment by siikamiika** [comment]
I usually use this repo for stuff that's not very organized, and didn't expect the danmaku tool to be this popular.

Anyway, software and libraries that I use are

- Linux (shoud work with any OS though)
- [Python 3](https://www.python.org/downloads/)
- [mpv](https://mpv.io/installation/)
- [pytz for Python 3](https://pypi.org/project/pytz/)
- [requests for Python 3](https://pypi.org/project/requests/)
- [FontForge](https://fontforge.org/en-US/)
- [ImageMagick](https://imagemagick.org/script/download.php)
- [Potrace](http://potrace.sourceforge.net/#downloading)
- [OpenMoji](https://openmoji.org/)
- Maybe I missed something and the script will complain about it

I also tried to fork [libass](https://github.com/libass/libass) to support actual images without tracing vector images from custom chat emoji, but that wasn't successful yet. There's an open issue about it here https://github.com/libass/libass/issues/73. It would also enable regular color emoji support, but now we need non-colored OpenMoji or similar.

How I run it:

```sh
./youtube-live-chat-danmaku-ass.py input.live_chat.json output.ass
mv output.ass /where/you/have/the/video/video.ass
./images_to_font.py # adds a font to ~/.local/share/fonts/LiveChat.ttf, other operating systems use different paths
cd /where/you/have/the/video
mpv video.mp4 # will automatically load video.ass
```

You can skip the image --> font tracing step if you edit the script a bit, cutting dependencies to a half:

```diff
diff --git a/danmaku/youtube-live-chat-danmaku-ass.py b/danmaku/youtube-live-chat-danmaku-ass.py
index bb62377..5be327d 100755
--- a/danmaku/youtube-live-chat-danmaku-ass.py
+++ b/danmaku/youtube-live-chat-danmaku-ass.py
@@ -405,13 +405,9 @@ class YoutubeLiveChatReplayParser:
             if 'text' in run:
                 return run['text']
             if 'emoji' in run:
-                best_thumbnail = None
-                for thumbnail in run['emoji']['image']['thumbnails']:
-                    if best_thumbnail is None:
-                        best_thumbnail = thumbnail
-                    elif best_thumbnail['width'] < thumbnail['width']:
-                        best_thumbnail = thumbnail
-                return chr(int(self._custom_emoji_mapper.get_mapping(best_thumbnail['url'])))
+                # todo download and embed image
+                emoji_shortcuts = sorted(run['emoji']['shortcuts'], key=lambda s: (s.startswith(':_') + 1) * len(s))
+                return emoji_shortcuts[0] if len(emoji_shortcuts) > 0 else ''
         return ''.join(map(map_run, data['runs']))

     def _parse_badge_types(self, data):
```
